import type { Metadata } from "next";
import "./globals.css";
import Providers from "./Providers";
import { Search } from "lucide-react";
import SearchMedia from "@/components/ui/SearchMedia";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta name="viewport" content="initial-scale=1, width=device-width" />
      <body className={` antialiased`}>
        {/* The Providers component wraps the children with the QueryClientProvider */}
        {/* to provide the query client context to the application. */}
        {/* It allows the use of React Query hooks in the children components. */}
        <Providers>
          <div className="relative min-h-screen grid grid-rows-[auto_1fr] ">
            {/* Include a header that has the Title of the app and logo. It should not be constrained
          by the app-wrapper*/}
            <header className="bg-navy-blue   text-white p-4 flex items-center justify-between">
              <h1 className="text-2xl  font-bold">TV Progress Tracker</h1>
              <SearchMedia />
            </header>
            <div className="app-wrapper ">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
